### ISSUE TITLE
Color Picker doesn't show up anymore

### ISSUE THREAD

**Issue by Ghaleon** [weslly/ColorPicker#43]
OS: Windows 7 - 64bits;
Sublime Version: 2.0.2;

It was working just great, but today morning, I tried to use it and wasn't working anymore... 

I installed Control Package, installed Color Picker and Emmet.

I sent this command on log: 

sublime.log_commands(True)
sublime.log_input(True)

And received this:
key evt: shift+control+c
command: color_picker

any idea? Thanks!

I installed de ST3 and now I'm getting this error:

line 293, in run
NameError: global name 'CHOOSECOLOR' is not defined

**Comment by GroxTheProgrammer** [comment]
I have installed color picker but it doesn't work. It does nothing, prints out nothing in the console, neither the shortcut or trying to load through Package Control doesn't also work. It is like I never installed this package! Please help!

**Comment by toewailin** [comment]
![image](https://user-images.githubusercontent.com/23572867/30986807-4e162b48-a4c7-11e7-9f93-a6404d298806.png
where is color picker? i can find ? snippet command already exit, but i can't find, how can i  do for this? please help!
