### ISSUE TITLE
Stopped working on selection (Linux)

### ISSUE THREAD

**Issue by tarpan** [weslly/ColorPicker#48]
I have been using ST2 for a few months and everything worked fine until today. ColorPicker does not show when a hex value is selected. Otherwise it shows up on the usual ctrl+shift+c combination.

**Comment by eyalzek** [comment]
LinuCC's fix worked for me on ST2 (Xubuntu 14.04)

**Comment by mstrcnvs** [comment]
@eyalzek can you test my version? It maintains backwards compatibility. So we can have a merge in the near future. Thank you!

**Comment by eyalzek** [comment]
@mstrcnvs it seems to be working fine

**Comment by weslly** [comment]
I've been using VIM for the last few months but I came back to sublime this week. I'll take a look at the issue(s) and merge the fixes as soon as possible (probably this week or so). Sorry for the waiting.

**Comment by mstrcnvs** [comment]
Cheers @weslly!

**Comment by slavugan** [comment]
ubuntu 14.10 x64 plugin dont start if cursor placed on any color code, but if cusor don't point on color the plugin starts good. For some reasons it can't pick color from sublime. On ST2 and ST3 result the same.

**Comment by markandrewj** [comment]
Wanted to confirm this behaviour "ubuntu 14.10 x64 plugin dont start if cursor placed on any color code, but if cusor don't point on color the plugin starts good. For some reasons it can't pick color from sublime. On ST2(2221) and ST3(3065) result the same." on 14.04.1

**Comment by mstrcnvs** [comment]
@slavugan @markandrewj Hi guys, can you test my working version? So that we can get a merge? It should work with cursor placed on a color code.

**Comment by slavugan** [comment]
@mstrcnvs Where can I take your working version for test?

**Comment by mstrcnvs** [comment]
@slavugan http://github.com/mstrcnvs/ColorPicker

**Comment by slavugan** [comment]
@mstrcnvs it works good, so you can merge ))

**Comment by Rob-ot** [comment]
You guys rock!

**Comment by weslly** [comment]
The fix was merged and released.

**Comment by markandrewj** [comment]
sorry I didn't have a moment to test, glad the bug has been closed, ty for patching
