### ISSUE TITLE
Windows ColorPicker not very efficient

### ISSUE THREAD

**Issue by legnaleama** [weslly/ColorPicker#63]
I've been using ColorPicker on Mac for quite a long time and I love it! The main usage I give is when I have to customize my company's App for different clients, I would just go to their sites and directly pick their main corporate colors using the GUI of ColorPicker without even leaving my Sublime active window. Just great.

The thing is that I've just downloaded the package for my personal Windows machine and... it sucks, I know CP uses the default color paletter of the OS but... <strong>is there any way of making the Windows Color Picker work the same way as the IOS does? </strong>

Thanks!

**Comment by weslly** [comment]
Updated at latest release
