### ISSUE TITLE
Windows 8.1 Net framework 4.0

### ISSUE THREAD

**Issue by CristianH033** [weslly/ColorPicker#72]
In Windows 8.1 can´t open the "win_colorpicker.exe" file in the lib  folder because it need net framework 3.

**Comment by weslly** [comment]
I'll take a look, but meanwhile, you can use the alternate colorpicker:

Open: `Preferences -> Package Settings -> ColorPicker -> Settings - User`

And set `"win_use_new_picker"` to `false`.

**Comment by CristianH033** [comment]
thank you from Colombia :)

**Comment by facelessuser** [comment]
Yeah, the code was built with an older .net.  I can try and build with a newer one.  I avoided it because I didn't want to have to upgrade the entire codebase if there were incompatibilities.  I need to publicly post it...

**Comment by facelessuser** [comment]
Looks like it builds fine in .NET 4.5.1 and seems to work fine, so I will make a new pull request with latest version when I get a chance.  I will also post the project somewhere so people can get access to it.

**Comment by facelessuser** [comment]
Rebuilt win_colorpicker.exe with .NET 4.5.1 https://github.com/weslly/ColorPicker/commit/2975d908a2684beea6438285acc093ee075915bd.  So when @weslly wants to release it, you should get the new one.  Within the next week, I will try and upload the project to bitbucket or something.

**Comment by weslly** [comment]
@facelessuser I tested the new binary on Windows XP (32bit) and got this error:

    OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by facelessuser** [comment]
Hmm.  I'll check it out. Maybe I accidentally built it as a 64 bit program.

**Comment by facelessuser** [comment]
Yeah, it looks like I built it as a 64 bit.  My bad.  I'll rebuild and confirm its 32 bit and then recommit.

**Comment by facelessuser** [comment]
I apologize about not getting this updated yet.  It is on my list for this weekend.

**Comment by weslly** [comment]
@facelessuser No worries, thanks for your help :)

**Comment by facelessuser** [comment]
Updated app as a 32 bit app https://github.com/weslly/ColorPicker/commit/371f601f1182845b79d61e5982af03107669d641.

Hopefully that fixes things.

**Comment by weslly** [comment]
@facelessuser Thanks for the update! I only had time to reinstall a VM with win XP now, and it seems to be working without any problems.

**Comment by weslly** [comment]
@facelessuser  Actually, for some reason package control wasn't getting the latest release so it worked with the previous build before 2975d90, but if it worked for you at newer windows versions and only one person (besides me) had this bug, I think it is safe to leave it as it is since Windows XP is almost 15 years old and not even Microsoft supports it anymore. Also, there's the ctypes alternative which works just fine.
