### ISSUE TITLE
Update hexa color value seem broken - Linux / Debian Wheezy (Crunchbang)

### ISSUE THREAD

**Issue by leNEKO** [weslly/ColorPicker#73]
After color selection, the hex color value from the color picker is not sent to the editor. No error appears in the console.

Sublime build 3084 / Dev channel.

**Comment by lapega** [comment]
Happens the same to me on Ubuntu 14.04, ST 3083.
Even if I copy or select the color in the picker window, closing the picker window will empty the clipboard.

**Comment by leNEKO** [comment]
Did some more investigation, the bug seem to come from the `lib/linux_colorpicker.py` which tell this
```
Traceback (most recent call last):
  File "/home/neko/.config/sublime-text-3/Packages/ColorPicker/lib/linux_colorpicker.py", line 27, in <module>
    if color_sel.run() == getattr(Gtk, 'RESPONSE_OK', Gtk.ResponseType.Ok):
AttributeError: type object 'GtkResponseType' has no attribute 'Ok'
```

**Comment by tonjo** [comment]
Found the error! In a previous commit `Gtk.ResponseType.OK` was changed into `Gtk.ResponseType.Ok`, with k in Ok lowercase. Change it back uppercase and voila ;)

**Comment by leNEKO** [comment]
nice, thank you
