### ISSUE TITLE
color picker is hang my sublime text 3

### ISSUE THREAD

**Issue by akshayvinchurkar** [weslly/ColorPicker#77]
it just hang my sublime and freeze it after that editor is stuck and keep doing something in background loading started

**Comment by sinansays** [comment]
I'm having the same problem. Invoking ColorPicker immediately crashes my Sublime instance. Only killing the 'osx_colorpicker" applet unhangs Sublime.

**Comment by akshay12345vin** [comment]
in latest update developer i think fixed this issue now my sublime is no longer crash or freeze

**Comment by adaringdesign** [comment]
Still crashes on Sierra..

**Comment by oldjackson** [comment]
It crashes only when Sublime is in full screen. Pretty annoying though

**Comment by SeanLeeCai** [comment]
Still crashes on Sierra(10.13.3)...
sublime text 3 version is 3.1.1, build 3176
