### ISSUE TITLE
Update new windows color picker

### ISSUE THREAD

**Issue by ihodev** [weslly/ColorPicker#84]
Please, update windows color picker to [this one](https://github.com/Monnoroch/ColorHighlighter/pull/274). It looks more native and allows to pick color from the screen.

![1fe3ac28-72d3-11e5-8b22-6a37d5eebc20](https://cloud.githubusercontent.com/assets/9801624/19467325/480ea356-9519-11e6-8204-1f0b2e242519.PNG)

**Comment by weslly** [comment]
@oivva Looks great! I'll setup a windows vm to take a look.

**Comment by weslly** [comment]
Updated at latest release
