### ISSUE TITLE
Color Picker doesn't show up anymore

### ISSUE THREAD

**Issue by nickf2k** [weslly/ColorPicker#99]
I try pressing Ctrl+Shift+C** but Color Picker in Sublime Text 3 doesn't working. I opened console and send  "sublime.log_commands(True)
sublime.log_input(True)"
When i press Ctrl+Shift+C, it shows: 
command: color_pick
key evt: shift+control+c
but it shows nothing, no another window...
Help me plz!

**Comment by Allmedialab** [comment]
Hi,
What do you mean by reverse? When I install the plugin again it still installs the latest version that doesn't work!
Thanks,
David
